name: MKgacha
version: 1.3.1
main: mkgacha.MKgacha
commands:
  mkgacha:
    description: MKallcommand.
    usage: /<command>
    default: op
  mg:
    description: MKallcommand.
    usage: /<command>
    default: op
permissions:
  mkgacha.config:
    description: mkgacha-setting-permission
    default: op
  mkgacha.use:
    description: mkgacha-use
    default: true
